ezra-bible-app/ezra-bible-app

locales/fr/translation.json
Please have Cyrille check my work when he returns.
In addition, I have corrected a small typo in the existing French translation.
> dans un régions
to
> dans un région
=> New French translations, plus correction of a small typo

locales/fr/translation.json
I was planning to have a look at it in the weekend, but since it's urgent I've taken a look at it during my coffee break.
=> Find-all-occurrences French translation

locales/fr/translation.json, locales/nl/translation.json
These are the translations for:
- assign-last-tag
- loading-verse-translations
- limit-notes-display-size
=> New French and Dutch translations

locales/es/translation.json
Let me know if there is  something else to be fixed, if not, approve the PR.
=> Translations errors where fixed?

locales/es/translation.json
The Spanish translation for 0.16 is waiting for @Rodolinux revision to be merge into Master.
=> Es translations update

app/frontend/components/book_selection_menu.js, app/frontend/components/info_popup.js, app/frontend/components/options_menu.js, app/frontend/components/tags/tag_assignment_menu.js, app/frontend/components/tags/tag_selection_menu.js, app/frontend/controllers/module_search_controller.js, app/frontend/controllers/tab_controller.js, app/frontend/controllers/tags_controller.js, app/templates/verse_list.pug, css/main.css, css/toolbox.css, features/steps/spectron_helper.js, html/boxes.html, html/verse_list_tabs.html, index.html, package.json
Introducing FontAwesome with quite a few icons added: #61
=> Feature fa icons

app/frontend/components/book_selection_menu.js, app/frontend/components/options_menu.js, app/frontend/components/tags/tag_assignment_menu.js, app/frontend/components/tags/tag_selection_menu.js, app/frontend/components/text_size_settings.js, app/frontend/controllers/app_controller.js, app/frontend/controllers/module_search_controller.js, css/main.css, html/display_options_menu.html, html/verse_list_tabs.html, locales/en/translation.json
Closing #42, already merged with #195. Please close this only after #195 
That's how it looks:
=> Bible text size buttons

app/frontend/components/navigation_pane.js, app/frontend/controllers/app_controller.js, app/frontend/controllers/startup_controller.js, app/frontend/controllers/tab_controller.js, app/frontend/helpers/ui_helper.js, app/frontend/ui_models/tab.js
@zhuiks Would you mind testing this a bit?
There are three scenarios:
* Restoring scroll position when switching between existing tabs.
* Restoring scroll position when switching to the previous tab after adding a new tab.
* Restoring scroll position after app start.
=> Restore scroll position

app/frontend/controllers/notes_controller.js, app/frontend/controllers/tags_controller.js, app/frontend/helpers/verse_box_helper.js
=> fix notes indicator sync across tabs

app/frontend/components/book_selection_menu.js, app/frontend/components/config_option.js, app/frontend/components/info_popup.js, app/frontend/components/module_assistant/install_module_assistant.js, app/frontend/components/options_menu.js, app/frontend/components/tab_search/exact_phrase_highlighter.js, app/frontend/components/tab_search/single_word_highlighter.js, app/frontend/components/tab_search/tab_search.js, app/frontend/components/tags/assign_last_tag_button.js, app/frontend/components/tags/tag_assignment_menu.js, app/frontend/components/tags/tag_selection_menu.js, app/frontend/components/text_size_settings.js, app/frontend/controllers/app_controller.js, app/frontend/controllers/tab_controller.js, app/frontend/controllers/tags_controller.js, app/frontend/controllers/text_controller.js, app/frontend/controllers/translation_controller.js, app/frontend/ezra_init.js, app/frontend/helpers/ezra_helper.js, app/frontend/ipc/i18n_ipc_backend.js, app/frontend/startup.js
I moved few functions (html, waitUntilIdle) from global `window` props to separate module.
That way it's much easier to track what's going on in the code. 
I don't think there any bundle size or performance implications
I think I refactored all the files that mentioned those functions
=> Refactor utility functions

.github/workflows/test.yml, app/backend/database/migrations/20190610132341-updateTranslationLanguageCodes.js, app/backend/database/models/bibletranslation.js, app/frontend/components/module_assistant/install_module_assistant.js, app/frontend/components/module_assistant/remove_module_assistant.js, app/frontend/controllers/i18n_controller.js, app/frontend/helpers/ezra_helper.js, app/frontend/helpers/i18n_helper.js, app/frontend/helpers/sword_module_helper.js, app/lib/__tests__/language_mapper.spec.js, app/lib/language_mapper.js, jest.config.js, package.json
This fixes #203
It also introduces unit tests
=> Fix locale switch on Android

app/frontend/controllers/i18n_controller.js, app/frontend/ezra_init.js, app/frontend/helpers/ui_helper.js, app/frontend/platform/cordova_platform.js, app/frontend/startup.js, index.html, locales/de/translation.json, locales/en/translation.json, locales/es/translation.json, locales/fr/translation.json, locales/nl/translation.json, locales/ro/translation.json, locales/ru/translation.json, locales/sk/translation.json, locales/uk/translation.json
=> Localize android messages

app/frontend/helpers/i18n_helper.js
Fixes #203 "(undefined)" in locale switcher when switching back to English
=> fix i18nHelper.getLanguage logic for 'en' locale

app/frontend/components/module_assistant/assistant_helper.js
=> Install assistant info button

CONTRIBUTING.md, app/frontend/controllers/i18n_controller.js, locales/locales.json
This is transitional script, and it needs to be merged before https://github.com/ezra-bible-app/node-sword-interface/pull/20 and https://github.com/ezra-bible-app/ezra-bible-app/pull/406
=> i18nController / extract available locales list into separate json file

app/frontend/components/verse_selection.js, app/frontend/controllers/dictionary_controller.js
Note that we could avoid the additional dependency between VerseSelection and DictionaryController in the future once the concept of the EventController would be available. In that case the verse selection would simply be another event that the DictionaryController could subscribe too.
=> Highlight strongs elements in currently selected verse on Cordova

app/frontend/components/tags/tag_assignment_menu.js, app/frontend/controllers/tags_controller.js
=> Hide tag assignment menu after assignment changes

app/frontend/components/emoji_button_trigger.js
=> Fix emoji button trigger

app/backend/ipc/ipc_nsi_handler.js, app/frontend/controllers/module_search_controller.js, app/frontend/ipc/ipc_nsi.js, app/frontend/ui_models/tab.js, css/main.css, html/module_search_menu.html, locales/de/translation.json, locales/en/translation.json, locales/es/translation.json, locales/fr/translation.json, locales/nl/translation.json, locales/pt-BR/translation.json, locales/ro/translation.json, locales/ru/translation.json, locales/sk/translation.json, locales/uk/translation.json, package.json
This adds a search scope parameter to the module search function and will fix #518.
Currently that parameter has the following options:
* Whole Bible
* Old Testament
* New Testament
=> Implement search scope for module search function

app/frontend/components/module_assistant/assistant_steps_add_modules.js, app/frontend/helpers/sword_module_helper.js, locales/de/translation.json, locales/en/translation.json, locales/es/translation.json, locales/fr/translation.json, locales/nl/translation.json, locales/pt-BR/translation.json, locales/ro/translation.json, locales/ru/translation.json, locales/sk/translation.json, locales/uk/translation.json
=> Also show module repository in module detail listing

app/frontend/components/tags/tag_assignment_menu.js, app/frontend/components/tags/tag_selection_menu.js, app/frontend/controllers/tags_controller.js, app/templates/tag_list.pug, css/main.css, css/toolbox.css
The tag lists have been optimized a bit for touch screen use. This closes #532.
Tag assignment list:
- Increased size of buttons
- Increased space between buttons/checkboxes
- Increased space between tag lines
Tag selection list:
- Increased space between tag lines
=> Tag lists - style enhancements for Android

app/frontend/components/tool_panel/panel_buttons.js, app/frontend/startup.js, css/main.css
=> Refactor panel button optimizations

locales/ro/translation.json
Romanian Locale update for 1.4
=> Update Romanian Locale update for 1.4 

locales/fr/translation.json
=> French translations 1.4

locales/nl/translation.json
=> Dutch translations 1.4

app/frontend/components/tool_panel/panel_buttons.js, css/main.css, css/tool_panel.css
=> Fix portrait landscape handling

app/backend/database/models/note.js, app/backend/database/models/versereference.js, app/backend/ipc/ipc_db_handler.js, app/frontend/components/docx_export/docx_export.js, app/frontend/components/docx_export/export_controller.js, app/frontend/components/info_popup.js, app/frontend/helpers/export_helper.js, app/frontend/ipc/ipc_db.js, css/main.css, locales/de/translation.json, locales/en/translation.json, locales/es/translation.json, locales/fr/translation.json, locales/nl/translation.json, locales/pt-BR/translation.json, locales/ro/translation.json, locales/ru/translation.json, locales/sk/translation.json, locales/uk/translation.json, package.json
This fixes #508.
There is a new export button in the App info dialog under the headline "Special functions".
=> CSV Export of all user data

app/frontend/components/info_popup.js, app/frontend/helpers/sword_module_helper.js, main.js
Hello,
This PR is to fix [issue 352](https://github.com/ezra-bible-app/ezra-bible-app/issues/352).
I've new to this project, so am not sure if there is functionality for clickable URLs defined somewhere else in the codebase. If there is, would someone be able to point me to that functionality.
I continued my efforts assuming this functionality wasn't in the codebase already.
I've forked and made a branch "issue-352" that adds this functionality.
The code came from https://stackoverflow.com/a/1500501 and the Regex came from https://www.codegrepper.com/code-examples/whatever/use+regex+to+get+urls+from+string.
I'm sure there are some changes that will need to be made.
=> Issue 352 - Make URLs in Sword Module Description Clickable

app/frontend/components/docx_export/__tests__/__snapshots__/docx_controller.spec.js.snap, app/frontend/components/docx_export/docx_export.js, app/frontend/components/docx_export/export_controller.js, app/frontend/helpers/export_helper.js, package.json
=> Fix docx export

app/backend/ipc/ipc_nsi_handler.js, app/frontend/components/navigation_pane.js, app/frontend/components/options_menu/options_menu.js, app/frontend/controllers/app_controller.js, app/frontend/controllers/tab_controller.js, app/frontend/controllers/text_controller.js, app/frontend/helpers/sword_module_helper.js, app/frontend/ipc/ipc_nsi.js, app/frontend/ui_models/tab.js, package.json
This fixes #340.
For testing you need to set the book loading mode to "Open all books chapter-wise".
There are updates in `package.json` so you need to run `npm install`.
=> Pre-load section headers and allow navigation to sections from other chapters

locales/ro/translation.json
All requiered locale have been added
=> add romanian locale for App release v 1.5.0

locales/nl/translation.json
=> 1.5 Dutch Translations

locales/pt-BR/translation.json
Brazilian Portuguese Updated ;)
=> Locale update for 1.5 #624

locales/ru/translation.json, locales/uk/translation.json
=> uk, ru locale update

locales/es/translation.json
I'm sorry for the delay. 
Translation is updated, and one typo have been fixed in the triple check process :). 
Happy v1.5 release.
=> Spanish translation updated for v1.5

locales/es/translation.json
The Spanish translation is updated. Hope to see the new release, I think is going to shine.
=> Spanish Locale update for 1.6

locales/ro/translation.json
romanian updated texts for 1.6
=> add romanian locale for 1.6

locales/pt-BR/translation.json
=> Brazilian Portuguese translation for 1.6 update

locales/nl/translation.json
=> Dutch translations 1.6

locales/fr/translation.json
=> French Translations 1.6

.github/actions/build_ubuntu2204/action.yml, .github/workflows/build.yml, package.json, package_config/deb_config_ubuntu2204.json
=> Add packaging for Ubuntu 22.04 - this fixes 684

.github/actions/build_fedora35/action.yml, .github/workflows/build.yml, package.json, package_config/rpm_config_fedora35.json
=> Fedora 35/36 packaging support

locales/pt-BR/translation.json
Included translations:
general
database-size
back
bible-browser
delete-note
=> Updated pt-BR

app/backend/ipc/ipc_nsi_handler.js, app/frontend/components/module_assistant/update_repositories.js, app/frontend/components/options_menu/options_menu.js, app/frontend/controllers/app_controller.js, app/frontend/controllers/module_update_controller.js, app/frontend/ipc/ipc_nsi.js, css/main.css, html/display_options_menu.html, locales/de/translation.json, locales/en/translation.json, locales/es/translation.json, locales/fr/translation.json, locales/nl/translation.json, locales/pt-BR/translation.json, locales/ro/translation.json, locales/ru/translation.json, locales/sk/translation.json, locales/uk/translation.json, package.json
=> Module update functionality

.github/workflows/build.yml
=> Fix Fedora packaging

app/frontend/components/tags/tag_statistics.js, app/frontend/components/verse_list_popup.js, app/frontend/controllers/app_controller.js, app/frontend/helpers/verse_list_title_helper.js
=> Make tags in tag statistics panel clickable

app/frontend/components/info_popup.js, app/frontend/components/module_assistant/module_assistant.js, app/frontend/components/module_assistant/unlock_dialog.js, app/frontend/components/tags/tag_group_assignment_list.js, app/frontend/components/tags/tag_group_list.js, app/frontend/components/tags/tag_list.js, app/frontend/components/tags/tag_list_menu.js, app/frontend/components/verse_list_popup.js, app/frontend/controllers/db_sync_controller.js, app/frontend/controllers/fullscreen_controller.js, app/frontend/controllers/module_update_controller.js, app/frontend/controllers/tags_controller.js, app/frontend/helpers/ezra_helper.js, app/frontend/helpers/new_release_checker.js, app/frontend/helpers/ui_helper.js, app/frontend/ipc/ipc_db.js, app/frontend/platform/cordova_platform.js, css/main.css, css/mobile.css, css/tool_panel.css, html/tag_panel.html
=> Optimize dialog close icon on Android

locales/nl/translation.json
Addresses #836. 
Also translated something I apparently missed last time (show-tab-search), and changed an older translation for consistency.
=>  Add Dutch translations for 1.9.0

locales/fr/translation.json
=>  Add French translations for 1.9.0

locales/ru/translation.json, locales/uk/translation.json
=> Update uk and ru locales for version 1.9.0

locales/es/translation.json
Sorry for the delay, I have been busy with the school and work.
=> Spanish translation updated for v1.9.0

app/frontend/components/navigation_pane.js, app/frontend/components/options_menu/options_menu.js, app/frontend/components/text_field.js, app/frontend/components/verse_statistics_chart.js, app/frontend/controllers/module_search_controller.js, app/frontend/controllers/tab_controller.js, app/frontend/controllers/text_controller.js, app/frontend/controllers/verse_list_controller.js, css/main.css, css/mobile.css, html/boxes.html, html/display_options_menu.html, index.html, locales/de/translation.json, locales/en/translation.json, locales/es/translation.json, locales/fr/translation.json, locales/nl/translation.json, locales/pt-BR/translation.json, locales/ro/translation.json, locales/ru/translation.json, locales/sk/translation.json, locales/uk/translation.json
This fixes #852 and #853.
Open points:
=> Add option to show search results in popup

CHANGELOG.md, features/005_module_search.feature, package.json, package_config/deb_config_debian10.json, package_config/deb_config_debian11.json, package_config/deb_config_mint18.json, package_config/deb_config_ubuntu1804.json, package_config/deb_config_ubuntu1910.json, package_config/deb_config_ubuntu2004.json, package_config/deb_config_ubuntu2204.json, package_config/rpm_config_centos.json, package_config/rpm_config_fedora.json, package_config/rpm_config_fedora35.json, package_config/rpm_config_fedora37.json, package_config/rpm_config_opensuse_leap.json
=> Remove icu dependency on Linux

locales/nl/translation.json
=>  Add Dutch translations for 1.11.0

locales/fr/translation.json
=> Add French translations for 1.11.0

locales/ru/translation.json, locales/uk/translation.json
=> Locale updates for 1.11.0

locales/pt-BR/translation.json
=> Update translation for Brazilian Portuguese

locales/ro/translation.json
=> i18n(romanian): add translation for bible-browser item

locales/nl/translation.json
Addresses https://github.com/ezra-bible-app/ezra-bible-app/issues/944
=> Dutch translation for 1.12.0

locales/fr/translation.json
=> French translation for 1.12.0

locales/ru/translation.json, locales/uk/translation.json
=> Ukrainian and russian Translation Update for 1.12.0

app/frontend/components/verse_selection.js, app/frontend/platform/cordova_platform.js, app/frontend/platform/electron_platform.js
=> Copy verse text to clipboard with HTML formatting

app/frontend/components/trans_change_titles.js, app/frontend/controllers/app_controller.js, locales/de/translation.json, locales/en/translation.json, locales/es/translation.json, locales/fr/translation.json, locales/nl/translation.json, locales/pt-BR/translation.json, locales/ro/translation.json, locales/ru/translation.json, locales/sk/translation.json, locales/sl/translation.json, locales/uk/translation.json
=> Turn transChange types into localized titles (see #972)

app/frontend/components/tool_panel/translation_comparison.js, app/frontend/components/verse_selection.js, app/frontend/controllers/app_controller.js, app/frontend/controllers/translation_controller.js, app/frontend/helpers/section_label_helper.js, app/frontend/helpers/verse_box_helper.js, css/main.css, locales/de/translation.json, locales/en/translation.json, locales/es/translation.json, locales/fr/translation.json, locales/nl/translation.json, locales/pt-BR/translation.json, locales/ro/translation.json, locales/ru/translation.json, locales/sk/translation.json, locales/sl/translation.json, locales/uk/translation.json
=> Add copy function to translation comparison panel

locales/fr/translation.json
=> Add French translations 1.13.0

app/backend/ipc/ipc_general_handler.js, app/frontend/components/options_menu/options_menu.js, app/frontend/components/options_menu/select_option.js, app/frontend/components/text_size_settings.js, app/frontend/components/type_face_settings.js, app/frontend/controllers/app_controller.js, app/frontend/ipc/ipc_general.js, css/main.css, html/boxes.html, html/display_options_menu.html, locales/de/translation.json, locales/en/translation.json, locales/es/translation.json, locales/fr/translation.json, locales/nl/translation.json, locales/pt-BR/translation.json, locales/ro/translation.json, locales/ru/translation.json, locales/sk/translation.json, locales/sl/translation.json, locales/uk/translation.json, package.json
=> Config dialog for changing Bible text type face

app/frontend/components/tool_panel/commentary_panel.js, css/main.css, css/tool_panel.css, locales/en/translation.json
=> Add button for copying commentary content to clipboard

locales/nl/translation.json
Addresses #1047
I had missed the initial issue in a flood of other e-mails.
=> Dutch translations 1.14.0

locales/fr/translation.json
Addresses #1047
I had missed the initial issue in a flood of other e-mails.
=> French translations 1.14.0

.github/actions/build_ubuntu2404/action.yml, .github/workflows/build.yml, package.json, package_config/deb_config_ubuntu2404.json
=> Add package for Ubuntu 24.04

locales/ro/translation.json
=> [locale]-add romanian locale update for 1.14.0

locales/ru/translation.json, locales/uk/translation.json
=> Uk, ru locale update for 1.14

app/frontend/components/options_menu/options_menu.js, app/frontend/controllers/theme_controller.js, html/display_options_menu.html, locales/de/translation.json, locales/en/translation.json, locales/es/translation.json, locales/fr/translation.json, locales/nl/translation.json, locales/pt-BR/translation.json, locales/ro/translation.json, locales/ru/translation.json, locales/sk/translation.json, locales/sl/translation.json, locales/uk/translation.json, main.js
=> Add system theme option on macOS

app/frontend/components/tags/tag_group_list.js, app/frontend/components/tags/tag_list_menu.js, app/frontend/event_types.js, html/tag_panel.html, html/tag_selection_menu.html
=> All tags link

app/frontend/components/tags/tag_distribution_matrix.js, app/frontend/components/tool_panel/commentary_panel.js, app/frontend/components/tool_panel/translation_comparison.js, app/frontend/components/verse_context_menu.js, app/frontend/components/verse_selection.js, app/frontend/controllers/app_controller.js, app/frontend/controllers/clipboard_controller.js, app/frontend/controllers/db_sync_controller.js, app/frontend/controllers/verse_list_controller.js, app/frontend/helpers/ui_helper.js, css/commentary_panel.css, css/main.css, css/tool_panel.css, html/tool_panel.html, html/verse_list_tabs.html, locales/de/translation.json, locales/en/translation.json, locales/es/translation.json, locales/fr/translation.json, locales/nl/translation.json, locales/pt-BR/translation.json, locales/ro/translation.json, locales/ru/translation.json, locales/sk/translation.json, locales/sl/translation.json, locales/uk/translation.json
=> Add button for copying current selection (text) or currently selected verse(s) to clipboard

app/frontend/components/verse_selection.js, app/frontend/controllers/clipboard_controller.js, app/frontend/controllers/dictionary_controller.js, app/frontend/controllers/longpress_controller.js, css/main.css
=> Enable text selection for verses that are selected

css/main.css
=> Fix: issue #1125 - wrapping text in Bible translation selection menu

.github/actions/build_opensuseleap15.5/action.yml, .github/actions/build_opensuseleap15.6/action.yml, .github/workflows/build.yml, package.json
=> Add build for OpenSuse Leap 15.6

app/frontend/components/options_menu/options_menu.js, css/main.css, html/display_options_menu.html, locales/de/translation.json, locales/en/translation.json, locales/es/translation.json, locales/fr/translation.json, locales/nl/translation.json, locales/pt-BR/translation.json, locales/ro/translation.json, locales/ru/translation.json, locales/sk/translation.json, locales/sl/translation.json, locales/uk/translation.json
=> Add 'Limit text width' option

locales/nl/translation.json
=> Dutch translations 1.16

locales/fr/translation.json
=> French translations 1.16

locales/ru/translation.json, locales/uk/translation.json
=> 1.16 Ukrainian and Russian locale updates

locales/es/translation.json
=> Update spanish translation

app/frontend/components/verse_context_menu.js, app/frontend/components/verse_selection.js, app/frontend/controllers/tab_controller.js, app/frontend/controllers/text_controller.js, app/frontend/controllers/translation_controller.js, app/frontend/startup.js, locales/de/translation.json, locales/en/translation.json, locales/es/translation.json, locales/fr/translation.json, locales/nl/translation.json, locales/pt-BR/translation.json, locales/ro/translation.json, locales/ru/translation.json, locales/sk/translation.json, locales/sl/translation.json, locales/uk/translation.json
=> Add context menu button for opening verse in new tab

app/frontend/components/options_menu/config_option.js, app/frontend/components/options_menu/options_menu.js, app/frontend/components/tool_panel/translation_comparison.js, app/frontend/components/verse_selection.js, app/frontend/helpers/verse_box_helper.js, html/display_options_menu.html, locales/de/translation.json, locales/en/translation.json, locales/es/translation.json, locales/fr/translation.json, locales/nl/translation.json, locales/pt-BR/translation.json, locales/ro/translation.json, locales/ru/translation.json, locales/sk/translation.json, locales/sl/translation.json, locales/uk/translation.json
=> Add option to copy verse reference before text

app/frontend/components/type_face_settings.js, css/main.css, css/mobile.css, css/verse_notes.css, html/boxes.html, locales/de/translation.json, locales/en/translation.json, locales/es/translation.json, locales/fr/translation.json, locales/nl/translation.json, locales/pt-BR/translation.json, locales/ro/translation.json, locales/ru/translation.json, locales/sk/translation.json, locales/sl/translation.json, locales/uk/translation.json
=> Make type face of user content (notes, tags) customizable
